module TestFailTryReturn2 {
   err X;

   fun TestFunApply[A](consume a:A):(a:A) {
       b = a;
       d = try {
           c = b;
           return c;
       } catch {
         .X => {
          return b;
         };
       };
       return d;
   };
}